In [27]:
import pandas as pd
from pandas import read_csv

path = '/Users/lujaynmegally/Desktop/DEA/GlobalPartners_project/data/'

date_dim = read_csv(path + 'date_dim.csv') 
order_item_options = read_csv(path + 'order_item_options.csv')
order_item = read_csv(path + 'order_items.csv')

In [28]:
def summary(df):
    return pd.DataFrame({
        "non_null_count": df.notna().sum(),
        "null_count": df.isna().sum(),
        'Data Type': df.dtypes,
        'Unique Values': df.nunique(),
        'Duplicates': df.duplicated().sum()})

In [29]:
date_dim.head()

,date_key,year,month,week,day_of_week,is_weekend,is_holiday,holiday_name
0,01-01-2023,2023,1,52,Sunday,True,True,New Year's Day
1,02-01-2023,2023,1,1,Monday,False,True,New Year's Day Observed
2,03-01-2023,2023,1,1,Tuesday,False,False,NaN
3,04-01-2023,2023,1,1,Wednesday,False,False,NaN
4,05-01-2023,2023,1,1,Thursday,False,False,NaN

In [30]:
summary(date_dim)

              non_null_count  null_count Data Type  Unique Values  Duplicates
date_key                 365           0    object            365           0
year                     365           0     int64              1           0
month                    365           0     int64             12           0
week                     365           0     int64             52           0
day_of_week              365           0    object              7           0
is_weekend               365           0      bool              2           0
is_holiday               365           0      bool              2           0
holiday_name              12         353    object             12           0

In [31]:
order_item_options.head()

,ORDER_ID,LINEITEM_ID,OPTION_GROUP_NAME,OPTION_NAME,OPTION_PRICE,OPTION_QUANTITY
0,6278eb58dfafab1e053fe172,6278eb63dfafab1e053fe18c,Cheese,American Cheese,0.0,1
1,6278eb58dfafab1e053fe172,6278eb63dfafab1e053fe18c,Veggies,Lettuce,0.5,1
2,6278eb58dfafab1e053fe172,6278eb63dfafab1e053fe18c,Veggies,Tomatoes,0.0,1
3,6278eb58dfafab1e053fe172,6278eb63dfafab1e053fe18c,Veggies,Onion,0.0,1
4,6278eb58dfafab1e053fe172,6278eb63dfafab1e053fe18c,Veggies,Green Peppers,0.0,1

In [32]:
summary(order_item_options)

,non_null_count,null_count,Data Type,Unique Values,Duplicates
ORDER_ID,193017,0,object,78614,2299
LINEITEM_ID,193017,0,object,102712,2299
OPTION_GROUP_NAME,193017,0,object,133,2299
OPTION_NAME,193017,0,object,637,2299
OPTION_PRICE,193017,0,float64,16,2299
OPTION_QUANTITY,193017,0,int64,1,2299

In [33]:
order_item.head()

,APP_NAME,RESTAURANT_ID,CREATION_TIME_UTC,ORDER_ID,USER_ID,PRINTED_CARD_NUMBER,IS_LOYALTY,CURRENCY,LINEITEM_ID,ITEM_CATEGORY,ITEM_NAME,ITEM_PRICE,ITEM_QUANTITY
0,Alltown Fresh,63bc98a7519adc105105a990,2023-03-08T11:03:32.223Z,64086b8463905bf310002079,63ee144950286a8367041911,NaN,False,USD,64086b84d5fbd8718a0717e6,Breakfast,Bacon Egg & Cheese*,5.99,1
1,Alltown Fresh,5f6a6c1537ab46bd38e9df75,2023-05-13T12:45:00.475Z,645f864c1c4b0312f10cfa75,NaN,NaN,False,USD,645f869568ab8e534e099ea7,Breakfast,Breakfast Burrito*,7.99,1
2,Alltown Fresh,5fece84aadb0d51509c36f22,2023-02-03T07:15:28.519Z,63dcb490665d80c6be09a618,5ece77fe902ad501337b23fd,NaN,False,USD,63dcb49b665d80c6be09a657,Breakfast,Bacon Egg & Cheese*,5.99,1
3,Alltown Fresh,5f6a6c1537ab46bd38e9df75,2023-08-17T16:18:02.231Z,64de483a7028adc2520d8cf0,NaN,NaN,False,USD,64de484eb7b035d89d004141,Salads,Greek Salad,11.99,1
4,Alltown Fresh,622107b40ac81503e0369ca6,2023-08-20T16:02:12.518Z,64e23904baef31a741016be9,NaN,NaN,False,USD,64e2395465826c9b650c1c37,Breakfast,Breakfast Burrito*,5.99,1

In [34]:
summary(order_item)

,non_null_count,null_count,Data Type,Unique Values,Duplicates
APP_NAME,203519,0,object,3,0
RESTAURANT_ID,203519,0,object,28,0
CREATION_TIME_UTC,203519,0,object,131328,0
ORDER_ID,203519,0,object,131328,0
USER_ID,185711,17808,object,20174,0
PRINTED_CARD_NUMBER,46084,157435,float64,5866,0
IS_LOYALTY,203519,0,bool,2,0
CURRENCY,203519,0,object,1,0
LINEITEM_ID,203518,1,object,203518,0
ITEM_CATEGORY,203518,1,object,45,0
ITEM_NAME,203518,1,object,431,0
ITEM_PRICE,203519,0,float64,636,0
ITEM_QUANTITY,203519,0,int64,39,0

In [35]:
order_item['subtotal'] = order_item['ITEM_PRICE'] * order_item['ITEM_QUANTITY']
print(order_item.groupby('ORDER_ID')['subtotal'].sum())

ORDER_ID
5e9f41ec505ee9c65088f162    92.79
5e9f42aa4f5ee95e12c276b0    21.19
5eaaff9f505ee909497b241b     4.99
5eab156e902ad5323d7b23d5     4.99
5eab19e8902ad559487b23d7    21.19
                            ...
65d518f4548f4f710c06127c    18.98
65d5219f70affc6bc20298cd    19.98
65d52c67bbe9d713e10147a9     3.99
65d5624413f20fce84013099    12.98
65d56573719ce34d2a0b3508    12.98
Name: subtotal, Length: 131328, dtype: float64

In [38]:
# 1. Create a new column for the line item total
print(order_item['CREATION_TIME_UTC'].sort_values(ascending=False).head(10))

157117    2024-02-21T02:52:35.366Z
157118    2024-02-21T02:52:35.366Z
174913    2024-02-21T02:39:00.056Z
174914    2024-02-21T02:39:00.056Z
15768     2024-02-20T22:49:11.022Z
150940    2024-02-20T22:03:11.796Z
150941    2024-02-20T22:03:11.796Z
130474    2024-02-20T21:26:12.327Z
130475    2024-02-20T21:26:12.327Z
163439    2024-02-20T20:18:30.043Z
Name: CREATION_TIME_UTC, dtype: object

In [50]:
freeorder_item = order_item[order_item['ITEM_PRICE'] == 0]
print(freeorder_item['ITEM_NAME'])

2460      HIPPEAS WHITE CHEDDAR CHICKPEA PUFFS
2461                                PEPSI 20OZ
2941                      Fresh Classic* | VEG
4213                                Chop Salad
5722              Tomato Soup & Grilled Cheese
                          ...
194888                          Smoked B.L.A.T
196409                       Smokehouse Burger
197603                                 Defense
199245    Smoked Ham & Hot Honey Egg & Cheese*
201955               SIMPLY APPLE JUICE 11.5OZ
Name: ITEM_NAME, Length: 156, dtype: object

In [44]:
# 1. Get unique names for options with 0 price
free_option_names = set(order_item_options[order_item_options['OPTION_PRICE'] == 0]['OPTION_NAME'].unique())

# 2. Get unique names for options with price > 0
paid_option_names = set(order_item_options[order_item_options['OPTION_PRICE'] > 0]['OPTION_NAME'].unique())

# 3. Find the overlap (Items that are sometimes free and sometimes paid)
overlap = free_option_names.intersection(paid_option_names)

# 4. Find unique "Always Free" items (Potential fixed discounts or complimentary items)
always_free = free_option_names - paid_option_names

print(f"Total Unique 'Free' Options: {len(free_option_names)}")
print(f"Total Unique 'Paid' Options: {len(paid_option_names)}")
print(f"Number of overlapping items: {len(overlap)}")

if len(overlap) > 0:
    print("\n--- Overlapping Items (Sometimes Discounted) ---")
    print(list(overlap)[:10]) # Showing first 10

if len(always_free) > 0:
    print("\n--- Always Free Items (Standard Comps) ---")
    print(list(always_free)[:10])

Total Unique 'Free' Options: 567
Total Unique 'Paid' Options: 136
Number of overlapping items: 66

--- Overlapping Items (Sometimes Discounted) ---
['Add Pea Protein', 'Add Egg', 'Add Chocolate', 'Add Dried Fruit', 'Add Hazelnut', 'Multigrain', 'Fresh Berries', 'French Vanilla', 'Add Chia Seeds', 'Fresh Avocado']

--- Always Free Items (Standard Comps) ---
['Add Spinach', 'Enoki Mushrooms', 'Scrambled Eggs', 'Add Cran/Orange Relish', 'Add Meat, Substitute Wild Mushroom', 'Dragon Fruit', 'Blueberries', 'No Parmesan Frico', 'Meat, Substitute Tofu', 'Romaine Hearts']

In [56]:
print ( order_item[order_item['USER_ID'].isin(order_item['USER_ID'].unique())].count() )

APP_NAME               203519
RESTAURANT_ID          203519
CREATION_TIME_UTC      203519
ORDER_ID               203519
USER_ID                185711
PRINTED_CARD_NUMBER     46084
IS_LOYALTY             203519
CURRENCY               203519
LINEITEM_ID            203518
ITEM_CATEGORY          203518
ITEM_NAME              203518
ITEM_PRICE             203519
ITEM_QUANTITY          203519
subtotal               203519
dtype: int64